### PR TITLE
Rebrand to BlahajASM

### PR DESCRIPTION
**Pull request by unnecessarymb**
I tried to be careful not to break the API, changelog, URLs, or similar, though the modID and other identifiers were changed out of pragmatism. Please comment if you need this done a bit differently, I am very fast with context-sensitive replacement thanks to my skill in regex replacement.

### CODE REVIEW

**Comment by unnecessarymb** [comment]
I got the pluralization rule wrong, let me fix that RQ. It should be Blahajs since it is an Americanized loanword.

**Comment by SylvKT** [comment]
blåhaj*

**Comment by unnecessarymb** [comment]
> blåhaj*

I'm going off of English internet slang: <https://en.wiktionary.org/wiki/blahaj#English>

**Comment by Rongmario** [comment]
Rebranding coming soon, thank you for the PR!

**Pull request closed without merging**
